builds:
  - binary: starling-cli
    goos:
      - darwin
      - linux
    goarch:
      - amd64

archive:
  replacements:
    darwin: macOS
    386: 32-bit
    amd64: 64-bit
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip

brew:
  github:
    owner: billglover
    name: homebrew-tap
  commit_author:
    name: Bill Glover
    email: bill@billglover.co.uk
  folder: Formula
release:
  prerelease: true 

changelog:
  filters:
    exclude:
      - '^docs:'
      - typo
      - (?i)foo
  sort: asc